name: 'd_classified'
version: '1.0.0'

profile: 'd_classified'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  d_classified:
    staging:
      +schema: staging
    intermediate:
      +schema: intermediate
    marts:
      +schema: marts